;; Loot Rarity Distribution
;; This file contains the default rarity distribution for Loot Spillage MCM Expansion

; Common

Keyword = LS_CommonLoot|Armor|ArmorMaterialStormcloak,ArmorMaterialForsworn,ArmorClothing,ArmorMaterialSteel,VendorItemAnimalHide,ArmorMaterialHide,ArmorMaterialImperialHeavy,ArmorMaterialImperialLight,ArmorMaterialImperialStudded,ArmorMaterialIron,ArmorMaterialIronBanded,ArmorMaterialLeather,ArmorMaterialStudded|-E

Keyword = LS_Common|Weapon|WeapMaterialDraugr,WeapMaterialDraugrHoned,WeapMaterialFalmer,WeapMaterialImperial,WeapMaterialIron,WeapMaterialSteel,WeapMaterialWood,WeapTypeStaff|-E

; Uncommon

Keyword = LS_UncommonLoot|Armor|ArmorMaterialStormcloak,ArmorMaterialForsworn,ArmorClothing,ArmorMaterialSteel,VendorItemAnimalHide,ArmorMaterialHide,ArmorMaterialImperialHeavy,ArmorMaterialImperialLight,ArmorMaterialImperialStudded,ArmorMaterialIron,ArmorMaterialIronBanded,ArmorMaterialLeather,ArmorMaterialStudded|E
Keyword = LS_UncommonLoot|Armor|DLC1ArmorMaterialDawnguard,DLC2ArmorMaterialMoragTong,ArmorMaterialThievesGuild,ArmorDarkBrotherhood,ArmorMaterialBlades,ArmorMaterialPenitus,ArmorMaterialOrcish,ArmorMaterialElven,DLC2ArmorMaterialChitinHeavy,DLC2ArmorMaterialChitinLight,DLC2ArmorMaterialBonemoldHeavy,DLC2ArmorMaterialBonemoldLight,ArmorMaterialScaled|-E
Keyword = LS_UncommonLoot|Armor|*ArmorLinwe,dunRatwayBrawlerGloves,ArmorClothing+*Adept

Keyword = LS_UncommonLoot|Weapon|WeapMaterialDraugr,WeapMaterialDraugrHoned,WeapMaterialFalmer,WeapMaterialImperial,WeapMaterialIron,WeapMaterialSteel,WeapMaterialWood,WeapTypeStaff|E
Keyword = LS_UncommonLoot|Weapon|DLC2NordicPickaxe,WeapMaterialDraugrHoned,WeapMaterialFalmerHoned,WeapMaterialOrcish,WeapMaterialSilver|-E

; Rare

Keyword = LS_RareLoot|Armor|DLC1ArmorMaterialDawnguard,DLC2ArmorMaterialMoragTong,ArmorMaterialThievesGuild,ArmorDarkBrotherhood,ArmorMaterialBlades,ArmorMaterialPenitus,ArmorMaterialOrcish,ArmorMaterialElven,DLC2ArmorMaterialChitinHeavy,DLC2ArmorMaterialChitinLight,DLC2ArmorMaterialBonemoldHeavy,DLC2ArmorMaterialBonemoldLight,ArmorMaterialScaled|E
Keyword = LS_RareLoot|Armor|ArmorMaterialGlass,ArmorMaterialDwarven,ArmorMaterialEbony,ArmorMaterialElvenGilded,ArmorMaterialSteelPlate,DLC2ArmorMaterialNordicHeavy,DLC2ArmorMaterialNordicLight,DLC2ArmorMaterialStalhrimHeavy,DLC2ArmorMaterialStalhrimLight|-E
Keyword = LS_RareLoot|Armor|ArmorClothing+*Expert|E

Keyword = LS_RareLoot|Weapon|DLC2NordicPickaxe,WeapMaterialDraugrHoned,WeapMaterialFalmerHoned,WeapMaterialOrcish,WeapMaterialSilver|E
Keyword = LS_RareLoot|Weapon|WeapMaterialEbony,WeapMaterialDwarven,WeapMaterialGlass,DLC2WeaponMaterialNordic,DLC2WeaponMaterialStalhrim|-E

; Epic

Keyword = LS_EpicLoot|Armor|ArmorMaterialGlass,ArmorMaterialDwarven,ArmorMaterialEbony,ArmorMaterialElvenGilded,ArmorMaterialSteelPlate,DLC2ArmorMaterialNordicHeavy,DLC2ArmorMaterialNordicLight,DLC2ArmorMaterialStalhrimHeavy,DLC2ArmorMaterialStalhrimLight|E
Keyword = LS_EpicLoot|Armor|ArmorMaterialDaedric,ArmorMaterialDragonplate,ArmorMaterialDragonscale|-E
Keyword = LS_EpicLoot|Armor|ArmorClothing+*Master|E

Keyword = LS_EpicLoot|Weapon|WeapMaterialEbony,WeapMaterialDwarven,WeapMaterialGlass,DLC2WeaponMaterialNordic,DLC2WeaponMaterialStalhrim|E
Keyword = LS_EpicLoot|Weapon|WeapMaterialDaedric,DLC1WeapMaterialDragonbone|-E

; Legendary

Keyword = LS_LegendaryLoot|Armor|ArmorMaterialDaedric,ArmorMaterialDragonplate,ArmorMaterialDragonscale|E
Keyword = LS_LegendaryLoot|Weapon|WeapMaterialDaedric,DLC1WeapMaterialDragonbone|E
Keyword = LS_LegendaryLoot|Armor|MagicDisallowEnchanting

; Artifact

Keyword = LS_ArtifactLoot|Armor|DaedricArtifact
Keyword = LS_ArtifactLoot|Weapon|DaedricArtifact
